### ISSUE TITLE
get_transformed_color_image returns image that is all 0

### ISSUE THREAD

**Issue by The-ArdaS** [ibaiGorordo/pyKinectAzure#85]
Hi there,
I have a recording which is made by k4arecorder.
Getting depth and color images are fine, but when I try get_transformed_color_image, it returns a 4-channel image where all pixels are 0.

Any help is appreciated.

**Comment by ibaiGorordo** [comment]
If you need the transformed color image, the recorded image needs to be in BGRA32 format due to how the official SDK works. You need to change the record example so that `device_config.color_format = pykinect.K4A_IMAGE_FORMAT_COLOR_BGRA32`

More info: https://github.com/ibaiGorordo/pyKinectAzure/issues/71
